package com.agmtopy.axonsimple.gatewayimpl;

import com.alibaba.cola.logger.Logger;
import com.alibaba.cola.logger.LoggerFactory;
import com.agmtopy.axonsimple.common.event.DomainEventPublisher;
import com.agmtopy.axonsimple.domain.gateway.MetricGateway;
import com.agmtopy.axonsimple.domain.metrics.MetricItem;
import com.agmtopy.axonsimple.dto.domainevent.MetricItemCreatedEvent;
import com.agmtopy.axonsimple.gatewayimpl.database.MetricMapper;
import com.agmtopy.axonsimple.gatewayimpl.database.dataobject.MetricDO;
import com.agmtopy.axonsimple.convertor.MetricConvertor;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;

/**
 *  领域对象网关的实现层
 */
@Component
public class MetricGatewayImpl implements MetricGateway {
    private static Logger logger = LoggerFactory.getLogger(MetricGatewayImpl.class);

    @Resource
    private MetricMapper metricMapper;

    @Resource
    private DomainEventPublisher domainEventPublisher;

    public void save(MetricItem metricItem){
        MetricDO metricDO = MetricConvertor.toDataObject(metricItem);
        metricMapper.create(metricDO);

        logger.debug("AutoGeneratedId: "+metricDO.getId());
        MetricItemCreatedEvent metricItemCreatedEvent = new MetricItemCreatedEvent();
        metricItemCreatedEvent.setId(metricDO.getId());
        metricItemCreatedEvent.setUserId(metricDO.getUserId());
        metricItemCreatedEvent.setMainMetricType(metricDO.getMainMetric());
        domainEventPublisher.publish(metricItemCreatedEvent);
    }
}
